---
title: "NOAA: Patterns of Climate in New York State, 1981-2010"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(plotly)
library(dplyr)
library(shiny)

knitr::opts_chunk$set(echo = FALSE)
```

```{r read}
#Read and clean data
noaa <- read_csv("./nynoaadat.zip")

noaa <-  noaa %>% 
  clean_names() %>% 
  mutate(tmax = as.numeric(tmax), tmin = as.numeric(tmin)) %>% 
  separate(date, c("year", "month", "day"), sep = "-") %>% 
  mutate(tmin = tmin / 10,
    tmax = tmax / 10,
    prcp = prcp / 10)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Average Maximum Temperature in New York State

```{r chart_a}
noaa %>%
  group_by(year) %>% 
  summarise(ave_max = round(mean(tmax, na.rm = TRUE), 2),
            range = round(max(tmax, na.rm = TRUE) - min(tmax, na.rm = TRUE), 2)) %>%
  mutate(text_label = str_c("Ave Max Temp: ", ave_max, '\nRange of Max Temps: ', range)) %>% 
  plot_ly(x = ~year, y = ~ave_max, type = "scatter", mode = "markers",
          alpha = 0.5, 
          text = ~text_label) %>% 
  add_lines(y = ~fitted(loess(ave_max ~ year)),
            line = list(color = '#07A4B5'),
            name = "Loess Smoother", showlegend = FALSE) %>% 
  layout(xaxis = list(title = "Year",
                      showticklabels = TRUE,
                      tickangle = 45),
                      margin = list(b = 48),
      yaxis = list(title = "Temperature (degrees Celsius)"))

min_temp = noaa %>% distinct(ave_max) %>% min()
max_temp = noaa %>% distinct(ave_max) %>% max()

# sliderInput widget
sliderInput("temperature_range", label = h3("Choose Temperature Range"), min = min_temp, 
        max = max_temp, value = c(12.91, 15.38))
 
year_choice = noaa %>% distinct(year) %>% pull()
```

Column {data-width=400}
-----------------------------------------------------------------------

### Precipitation in New York State by Five Year Intervals

```{r chart_b}
noaa %>% 
  filter(!is.na(prcp)) %>% 
  group_by(year) %>% 
  summarise(ave_rain = round(mean(prcp, na.rm = TRUE), 2)) %>%
  mutate(year = as.numeric(year),
         five_years = cut(year, breaks = 6)) %>% 
  plot_ly(y = ~ave_rain, color = ~five_years, type = "box",
          colors = "Set2") %>% 
  layout(xaxis = list(title = "Year Interval"),
      yaxis = list(title = "Precipitation (mm)"))

# radioButtons widget
radioButtons("year_choice", label = h3("Choose Year Range"),
    choices = year_choice, 
    selected = "five_years")
```

### Number of Days above 35 degrees C (95 degrees F) across New York State

```{r chart_c}
noaa_year_stats <- noaa %>% 
  group_by(year) %>% 
  summarise(tmax_year = max(tmax, na.rm = TRUE),
            ave_max_year = round(mean(tmax, na.rm = TRUE), 2),
            range = round(max(tmax, na.rm = TRUE) - min(tmax, na.rm = TRUE), 2),
            ave_min_year = round(mean(tmin, na.rm = TRUE), 2))

noaa %>% 
  group_by(year, month, day) %>% 
  summarize(tmax_day = max(tmax, na.rm = TRUE)) %>%
  filter(tmax_day > 35) %>% 
  group_by(year) %>% 
  count(year) %>% 
  left_join(., noaa_year_stats, by = "year") %>% 
  mutate(text_label = str_c("Max Temp: ", tmax_year, 
                            "\nAve Max Temp: ", ave_max_year, 
                            "\nAve Min Temp: ", ave_min_year, 
                            '\nRange of Max Temps: ', range)) %>%
  plot_ly(x = ~year, y = ~n, type = "bar", text = ~text_label) %>% 
  layout(xaxis = list(title = "Year",
        showticklabels = TRUE,
        tickangle = 45),
        margin = list(b = 48),
      yaxis = list(title = "Number of Days above 35 degrees C"))

year = noaa %>% distinct(year) %>% pull()

# selectInput widget
selectInput("year_choice", label = h3("Select Year"),
            choices = year, selected = "1981")
```

